{"uuid": "4fe8c2fc-6372-400c-9e6c-f58da81c4dd3", "children": ["f7db2cba-1670-48af-b3c6-a0f49f4ca550", "fddc75d3-53e6-4054-b4fe-d41d51c32c0f", "60f42f0f-e161-4fd1-89d1-0722196e0da7"], "befores": [{"name": "db", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)\")\n", "trace": "  File \"/home/julia/PycharmProjects/python_for_QA/venv/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/julia/PycharmProjects/python_for_QA/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/julia/PycharmProjects/python_for_QA/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/home/julia/PycharmProjects/python_for_QA/conftest.py\", line 44, in db\n    password=db_config[\"password\"])\n  File \"/home/julia/PycharmProjects/python_for_QA/fixture/db.py\", line 12, in __init__\n    self.connection = pymysql.connect(host=host, database=database, user=user, password=password, autocommit=True)\n  File \"/home/julia/PycharmProjects/python_for_QA/venv/lib/python3.6/site-packages/pymysql/__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"/home/julia/PycharmProjects/python_for_QA/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 325, in __init__\n    self.connect()\n  File \"/home/julia/PycharmProjects/python_for_QA/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 630, in connect\n    raise exc\n"}, "start": 1587565357346, "stop": 1587565357442}], "start": 1587565357346, "stop": 1587565357810}